### ISSUE TITLE
Can ?placeholder give us the raw image instead of an svg one ?

### ISSUE THREAD

**Issue by ephys** [timse/srcset-loader#6]
Instead of exporting a .svg containing a base64-encoded image, can you just export the base64-encoded image itself ?

The reasoning behind my request is that we might want to do something else than blur the tiny image, or do an animation on the svg itself.
Also, adding the blur after importing the image might reduce the bundle size as the svg part wouldn't be repeated in every image module.

Thank you :)

**Comment by ephys** [comment]
As we needed this feature for one of our projects, we forked srcset-loader and added add the option in a backward-compatible way, along with a few minor changes.

@timse Tell me if you're interested in merging the changes, I'll create a pull request so you can review them. I wrote a changelog [here](https://github.com/Ephys/srcset-loader/blob/master/CHANGELOG.md#v200) for a quick recap.

**Comment by timse** [comment]
heya, sure, just open a PR and we can check from there.
Sorry i am only responding now, your initial issue didnt cause any notifications :(

**Comment by ephys** [comment]
I think we can close this then. :)
